#pragma once

enum UserLoginStatus
{
    STATUS_LOGINING,
    STATUS_CONNECTING,
    STATUS_CONNECTED,
    STATUS_LOGIN_FINISHED,
    STATUS_ERROR,
    STATUS_GET_USER_LIST,  
    //趁着写吧下面是文件状态
    FILE_STATUS_CONNECTING,
    FILE_STATUS_CONNECTED,
    FILE_STATUS_ERROR,
    FILE_STATUS_SUCCESS,
    //趁着写吧下面是图片状态
    IMAGE_STATUS_CONNECTING,
    IMAGE_STATUS_CONNECTED,
    IMAGE_STATUS_ERROR,

};
