/**
 *  定义消息
 *
 *  @author zhangyi
 *  @since  2011-03-19
 */

#ifndef XP_UIBASE_UIEVENT_EVENTDEF_H
#define XP_UIBASE_UIEVENT_EVENTDEF_H

namespace PC
{
    enum EEventDef
    {
        EVT_BASE_WIDGET_ACTIVE,

        EVT_PUSH_BUTTON_MOUSEDOWN,
        EVT_PUSH_BUTTON_MOUSEMOVE,
        EVT_PUSH_BUTTON_MOUSEDRAG,
        EVT_PUSH_BUTTON_MOUSEUP,
        EVT_PUSH_BUTTON_CLICKED,
        EVT_PUSH_BUTTON_ENTER,
        EVT_PUSH_BUTTON_LEAVE,
        EVT_PUSH_BUTTON_FOCUS_OUT,

        EVT_SIMPLE_TEXT_CLICKED,
        EVT_SIMPLE_TEXT_SCALE_CHANGED,

        EVT_TRANSPORT_MOUSE_MOVE,
        EVT_TRANSPORT_MOUSE_PRESS,
        EVT_TRANSPORT_MOUSE_RELEASE,
        EVT_TRANSPORT_MOUSE_DOUBLECLICK,

        EVT_SCROLLBAR_VALUE_CHANGED,

        EVT_BASE_TABLE_SET_COLUMN_WIDTH,
        EVT_BASE_TABLE_SET_NUMBER_WIDTH,
        EVT_BASE_TABLE_SET_VSCROLL_VALUE,
        EVT_BASE_TABLE_SET_PANEL_WIDTH,
        EVT_BASE_TABLE_CUSTOMIZE_COLUMNS,
        EVT_BASE_TABLE_ADJUST_COLUMN_WIDTH,
        EVT_BASE_TABLE_ADJUST_ROW_HEIGHT,
        EVT_BASE_TABLE_SET_COLUMN_VISIBLE,
        EVT_BASE_TABLE_SET_COLUMN_LOCKED,
        EVT_BASE_TABLE_SET_COLUMN_TOOL_SHOW,
        EVT_BASE_TABLE_SET_COLUMN_TIP_CLICKED,
        EVT_BASE_TABLE_SET_COLUMN_FILTER_SHOW,
        EVT_BASE_TABLE_SORT_BY_COLUMN,
        EVT_BASE_TABLE_RAISE_COLUMN,
        EVT_BASE_TABLE_DRAG_COLUMN,
        EVT_BASE_TABLE_AUTO_MOVE_COLUMN,
        EVT_BASE_TABLE_MOVING_COLUMN_TEST_MOVE_SCROLL,
        EVT_BASE_TABLE_MOVING_COLUMN_TEST_STOP_SCROLL,
        EVT_BASE_TABLE_END_DRAG_MOVE_COLUMN,
        EVT_BASE_TABLE_RESET_COLUMNS,
        EVT_BASE_TABLE_RESET_ROWS,
        EVT_BASE_TABLE_RESET_FONT_SIZE,
        EVT_BASE_TABLE_HEADER_BUTTON_CLICKED,

        EVT_BASE_TABLE_RBUTTON_CLICKED,
        EVT_BASE_TABLE_VIEW_UPDATE,
        EVT_BASE_TABLE_VERTICAL_VIEW_UPDATE,
        EVT_BASE_TABLE_ROW_SELECT,
        EVT_BASE_TABLE_MULTI_ROW_SELECT,
        EVT_BASE_TABLE_ROW_DOUBLE_CLICKED,
        EVT_BASE_TABLE_TODELETE_ROW,
        EVT_BASE_TABLE_EDIT_FINISHING,
        EVT_BASE_TABLE_EDIT_FINISHED,
        EVT_BASE_TABLE_COLUMN_FILTER,
        EVT_BASE_TABLE_CELL_CLICKED,
        EVT_BASE_TABLE_HEADER_SHOW_MENU,
        EVT_BASE_TABLE_WIDGET_CELL_VALUE_CHANGE,
        EVT_BASE_TABLE_FONT_SETTING_FINISH,

        EVT_BASE_TABLE_ROWS_REMOVED,
        EVT_BASE_TABLE_LAYOUT_LOCK,                 // 表格布局锁定解锁
        EVT_BASE_TABLE_WIDGET_DELEGATE_UPDATE,
        EVT_BASE_TABLE_DELEGATE_SET_CURSOR,
        EVT_BASE_TABLE_DELEGATE_SHOW_TIPS,
        EVT_BASE_TABCONTROL_SHOW_TAB,
        EVT_BASE_SLIDER_VALUE_CHANGED,
        EVT_BASE_TABLE_ROW_COUNT_CHANGED,
        EVT_BASE_TABLE_COLUMNS_CHANGED,
        EVT_BASE_TABLE_HEADER_CHECK_BOX_STATE_CHANGED,     // 表头CCheckbox的状态改变

        EVT_CHECK_BOX_CLICKED,                  // CCheckbox的点击
        EVT_CHECK_BOX_STATE_CHANGED,            // CCheckbox的状态改变
        EVT_CHECK_BOX_FOCUS_IN,                 // CCheckBox获得焦点
        EVT_CHECK_BOX_FOCUS_OUT,                // CCheckBox失去焦点
        
        EVT_COMBO_BOX_CHANGE_INDEX,                 // CCombobox的选择下标改变
        EVT_COMBO_BOX_CHANGE_TEXT,                  // CCombobox的选择文字改变
        EVT_COMBO_BOX_ACTIVATE_INDEX,               // CCombobox的选择下标改变
        EVT_COMBO_BOX_ACTIVATE_TEXT,                // CCombobox的选择文字改变
        EVT_COMBO_BOX_EDIT_TEXT_CHANGED,            // CCombobox的文字改变
        EVT_COMBO_BOX_CURRENT_TEXT_CHANGED,         // CCombobox的当前文字改变
        EVT_COMBO_BOX_FOCUS_OUT,                    // CCombobox焦点移出
        EVT_COMBO_BOX_HIDE_POP,                     // CCombobox隐藏popup菜单
        EVT_COMBO_BOX_EDIT_RETURN_PRESSED,
        EVT_COMBO_BOX_SHOW_POP,

        EVT_LIST_VIEW_SELECTION_CHANGED,        // CListView选项改变(包括代码改变)
        EVT_LIST_VIEW_SELECTION_ACTIVATED,      // CListView选项改变(不包括代码改变)

        EVT_IMAGE_WIDGET_CLICKED,        
        EVT_SPIN_BOX_CHANGE_VALUE,

        EVT_DOUBLE_SPIN_BOX_CHANGE_VALUE,
        EVT_DOUBLE_SPIN_BOX_FOCUS_OUT,
        EVT_DOUBLE_SPIN_BOX_CANCEL_CHANGE,
        EVT_DOUBLE_SPIN_BOX_EDIT_FINISHED,

        EVT_INT_SPIN_BOX_CHANGE_VALUE,
        EVT_INT_SPIN_BOX_FOCUS_OUT,
        EVT_INT_SPIN_BOX_CANCEL_CHANGE,
        EVT_INT_SPIN_BOX_EDIT_FINISHED,

        EVT_CLICK_COMBO_BOX_ACTIVATE_INDEX,
        EVT_CLICK_COMBO_BOX_ACTIVATE_TEXT,

        EVT_RADIO_BUTTON_TOGGLED,
        EVT_RADIO_BUTTON_CLICKED,

        EVT_RADIO_BUTTON_GROUP_CHANGE_STATE,        // RadioButtonGroup的选择改变

        EVT_TIME_PERIOD_EDIT_FINISHED,
        EVT_TIME_PERIOD_EDIT_TYPE,

        EVT_LINEEDIT_EDITED,
        EVT_LINEEDIT_TEXT_CHANGED,
        EVT_LINEEDIT_EDITING_FINISHED,
        EVT_LINEEDIT_EDITING_RETURN_PRESSED,
        EVT_LINEEDIT_EDITING_RETURN_RELEASED,
        EVT_LINEEDIT_FOCUS_OUT,
        EVT_LINEEDIT_FOCUS_IN,
        EVT_LINEEDIT_CAPSLOCK,
        EVT_LINEEDIT_BEFORE_FOCUS_OUT,

        EVT_TEXTEDIT_TEXT_CHANGED,
        EVT_TEXTEDIT_SELECTION_CHANGED,
        EVT_TEXTEDIT_FOCUS_OUT,

        EVT_WIDGETLIST_UPDATE,
        EVT_WIDGETLIST_AT_END,

        EVT_WIDGETTABLE_AT_END,

        EVT_PARAMETER_CELL_EDIT_FINISHED,
        EVT_PARAMETER_CELL_UNIT_CLICKED,
        EVT_PARAMETER_CELL_INVALID_INT,
        EVT_PARAMETER_CELL_INVALID_DOUBLE,
        EVT_PARAMETER_CELL_TEXT_CHANGED,
        EVT_PARAMETER_CELL_UNIT_CHANGED,
        EVT_PARAMETER_CELL_VISIBLE_CHANGE,
        EVT_PARAMETER_CELL_INC_DEC_CLICKED,
        EVT_PARAMETER_CELL_EDIT_SETTING_PRECISION,
        EVT_PARAMETER_CELL_SETTING_PRECISION_BY_INC_DEC_CLICKED,

        EVT_WINDOW_SET_TITLE,

        EVT_MULTI_PARAM_WIDGET_PARAM_UPDATE,
        EVT_MULTI_PARAM_WIDGET_3RDALGO_PARAM_UPDATE,

        EVT_DOCK_HINT_UNLOCK,

        EVT_DOCK_TAB_PAGE_ACTIVATE,         // CDockTabPage激活
        EVT_DOCK_TAB_REMOVE,                // tab页移走
        EVT_DOCK_TAB_RECALC,                // dock tab的宽度和位置需要重新计算

        EVT_DOCK_GET_WINDOW_ICON,           // dock控件获取window icon
        EVT_DOCK_GET_WINDOW_TITLE,          // dock控件获取window icon

        EVT_DOCK_DOCKABLE_WIDGET_REMOVE,    // IDockableWidget移出
        EVT_DOCK_SUB_WIDGET_REMOVE,         // CDockWidget移出
        EVT_DOCK_WIDGET_CLOSE,              // IUiDockableWidget被从菜单中关闭
        EVT_DOCK_CONTAINER_SEPERATE,        // CDockContainer分解，只保留一个子控件
        EVT_DOCK_SUB_ELEMENT_CLEAR,         // 所有sub element移出
        EVT_DOCK_TAB_CLEAR,                 // 所有main tab移出

        EVT_DOCK_TAB_PAGE_SET_TITLE,
        
        EVT_DOCK_WIDGET_INSERT,             // 插入新的CDockWidget
        EVT_DOCK_WIDGET_SET_TITLE,
        EVT_DOCK_WIDGET_GET_ORIENTATION,

        EVT_DOCK_WIDGET_HEADER_ENTER,
        EVT_DOCK_WIDGET_HEADER_LEAVE,
        EVT_DOCK_WIDGET_HEADER_MOUSEMOVE,
        EVT_DOCK_WIDGET_HEADER_MOUSEPRESS,
        EVT_DOCK_WIDGET_HEADER_MOUSERELEASE,
        EVT_DOCK_WIDGET_HEADER_TITLE_CLICK,
        EVT_DOCK_WIDGET_RELEASE,
        EVT_DOCK_WIDGET_ACTIVE,
        EVT_DOCK_WIDGET_ACTIVATE_WINDOW,
        EVT_DOCK_WIDGET_FRAME,
        EVT_DOCK_WINDOW_CLOSE,
        EVT_DOCK_SET_WINDOW_TYPE_ID,

        EVT_DOCK_SET_WINDOW_TITLE,
        EVT_GET_MAINWINDOW,
        EVT_ACCOUNT_DO_MODIFY_PASSWORD,     // 账户面板修改密码提交

        EVT_STATUSBAR_ORDERSERVER_SAVE,             // 下单server保存
        EVT_STATUSBAR_ORDERSERVER_SAVE_AND_BOOT,    // 保存并启动

        EVT_USER_AGREEMENT_ACCEPTED,

        EVT_SEARCH_LINE_EDIT_TEXT_CHANGED,          // 搜索、过滤输入框文字发生变化
        EVT_SEARCH_LINE_EDIT_TEXT_EDITED,           // 搜索、过滤输入框文字被编辑
        EVT_SEARCH_LINE_EDIT_SEARCH_TEXT,           // 搜索、过滤输入框搜索按钮被点击

        EVT_TIMELINE_UPDATE_DISPLAY_REGION,         // 更新时间轴可视区域，用于宽度不超过一屏的更新
        EVT_TIMELINE_MOVE_DISPLAY_REGION,           // 更新时间轴可视区域，用于边界同时移动的更新，不限制宽度
        EVT_TIMELINE_APPROACHING_EDGE,              // 时间轴中的拖动滑块接近某一侧的边界
        EVT_TIMELINE_FARAWAY_EDGE,                  // 时间轴中的拖动滑块远离边界
        EVT_TIMELINE_UPDATE_REGION,                 // 用于向parent传递区域更新

        EVT_TREEWIDGET_CURRENT_ITEM_CHANGED,        //tree
        EVT_TREEWIDGET__ITEM_CLICKED,
        EVT_TREEWIDGET_ITEM_DOUBLE_CLICKED,
        EVT_GET_DOCK_WINDOW_DOCKABLEWIDGETS_NUM,    // 得到DOCK的数目

        EVT_INDEX_LOCK_EXPAND_WIDTH,                // 锁定界面CNavigationBarButton
        EVT_MOUSE_IN_NAVIGATION_BUTTON,             // 鼠标停留在导航栏上 

        EVT_MASKING_WIDGET_MOUSEMOVE,
        EVT_MASKING_WIDGET_MOUSEPRESS,

        EVT_DELETE_INDEX_WIDGET,
        EVT_UPDATE_INDEX_VIEW,
        EVT_HIGHLIGHT_INDEX_WIDGET,
        EVT_LOCK_CURSOR_KEYBOARD,
        EVT_KLINE_CURSOR_KEYBOARD_PRESS,
        EVT_KLINE_CANCLE_LINK_TICK_DATA,
        EVT_ADD_INDEX_WIDGET,
        EVT_RESIZE_HIGHLIGHT_WIDGET,
        EVT_UPDATE_INDEX_ID,
        EVT_TICK_DATA_CONNECT,
        EVT_MULTI_VIEW_DOUBLE_CLICKED,
        EVT_INDEX_CHANGE_DISPLAY_REGION,
        EVT_INDEX_STATISTIC_SELECT_REGION,
        EVT_RECEIVE_INDEX_DATA,
        EVT_MOVE_INDEX_VIEW,
        EVT_CHNAGE_INDEX_PERIOD,
        EVT_DR_TYPE_CHANGE,
        EVT_INIT_TIMELINE,
        EVT_UPDATE_TIMELINE,
        EVT_SHOW_EDIT_FORMULA_WIDGET,
        EVT_SUPERPOSED_STOCK,
        EVT_CANCEL_ADD_STOCK,
        EVT_RESET_INDEX_TITLE_SIZE,
        EVT_KLINE_LOCK_UNLOCK_CURSOR,
        EVT_INDEX_SWITCH_TO_DATE,
        EVT_SAVE_CURRENT_INDEXES,
        EVT_INDEX_SAVE_USER_CONFIG,
        EVT_DOUBLE_CLICKED_INDEX_WIDGET,         // 双击附图指标界面

        EVT_RADIO_TAB_GROUP_CHANGE_STATE,        // RadioButtonGroup的选择改变

        EVT_NAVIGATOR_SELECT_ITEM,
        EVT_MSG_SETTING_SELECT_ITEM,
        EVT_NAVIGATOR_UPDATE,
        EVT_REMOVE_POSITION_DOCK_WIDGET,        // 删除持仓窗口

        EVT_SET_FORMULA_FOR_MODEL,
        EVT_INIT_POSITION_VIEW,
        EVT_REMOVE_POSITION_PANEL,
        EVT_STATISTIC_SHOW_STOCKLIST,
        EVT_GET_LATEST_TRADE_DATE,  // 获取最新交易日
        EVT_GET_SETTING_MULTI_PERIOD, //获取设置中多周期设置

        EVT_TREE_RESET_LAYOUT,
        EVT_TREE_NODE_SELECT,
        EVT_TREE_NODE_SELECT_PARENT,

        EVT_DELEGATE_CHECK_BOX_STATE_CHANGED,
        EVT_DELEGATE_CHECK_BOX_CLICKED,
        EVT_DELEGATE_SIMPLE_TEXT_CLICKED,
        EVT_DELEGATE_PUSH_BUTTON_CLICKED,

        EVT_DELEGATE_LINEEDIT_FINISH,
        EVT_DELEGATE_LINEEDIT_SET,

        EVT_DELEGATE_DOUBLE_SPIN_BOX_FINISH,
        EVT_DELEGATE_DOUBLE_SPIN_BOX_SET,
        EVT_DELEGATE_DOUBLE_SPIN_BOX_CANCEL_CHANGE,

        EVT_DELEGATE_INT_SPIN_BOX_FINISH,
        EVT_DELEGATE_INT_SPIN_BOX_SET,
        EVT_DELEGATE_INT_SPIN_BOX_CANCEL_CHANGE,

        EVT_FOCUS_MOVE,
        EVT_SCREEN_CAPTURE_OPERATION_CANCEL,
        EVT_SCREEN_CAPTURE_OPERATION_OK,
        EVT_LINK_INVEST_DATA,
        EVT_RESET_MULTI_PARAM,
        EVT_DROPDOWN_SHOW_HELP,

        EVT_HPF_COL_DRAWLIST_CHANGED,
        EVT_DROPDOWNWIDGET_HIDE,
        EVT_DOCK_POP_DOCK_WINDOW,
        EVT_HPFTREETABLE_VHEADER_DELEGATE_PRESS,

        EVT_AUTOKEYBOARD_LINEEDIT_CHANGE,
        EVT_SMART_KEYBOARD_ITEM_CLICKED,

        EVT_SETTING_APPLYCONFIG,                    // 应用设置，不消失对话框
        EVT_MAIN_TOOLBAR_SYSTEM_SETTING,
        EVT_SPLIT_CONTAINTER_MOVE,                   // 拖动分割器
        EVT_SPLIT_FRONT_WIDGET_OPEN,                 // 打开前面的按钮
        EVT_SPLIT_AFTER_WIDGET_OPEN,                 // 打开后面的按钮
        EVT_SETTING_SHOW_CONST_PAGE,
        EVT_PAGING_QUERY,                           //分页查询

        EVT_SPLIT_CONTAINER_RESIZE,
        EVT_SEARCH_RETURN,                          //CSeniorSearch查询结束
        EVT_SELECT_PAIR_CLICKED,
        EVT_SCROLLBAR_USER_DRAGING,

        EVT_BASE_TABLE_ROW_MOUSE_MOVE,
        EVT_CANCEL_PAGE_UPDATE_DATA,
        EVT_EDIT_PORTFOLIO_NAME_FINESH,
        EVT_EDIT_ADD_PORTFOLIO_POSITION,
        EVT_EDIT_OPERATE_PORTFOLIO_POSITION,
        EVT_EDIT_OPERATE_PORTFOLIO_DEAL,
        EVT_EDIT_IMPORT_PORTFOLIO_POSITION,
        EVT_EDIT_QUERY_PORTFOLIO_OPERATION_RECORD,

        EVT_COMBOX_PARAMETER_CELL_CHANGED,
        EVT_IBANK_FINANVING_INFO_CHANGE,

        EVT_POP_DIALOG_SELECT,                  //弹出浮动对话框选择事件

        EVT_BASE_TABLE_COMBOX_CHANGED,

        EVT_CONST_KEYBOARD_CHANGED,
        EVT_MULTI_COMBO_BOX_CHANGE_TEXT,
        EVT_BASE_TABLE_HEADER_SHOW_FLOAT,      //表格头点击弹出浮动窗口

        EVT_DELEGATE_RADIOBUTTON_STATE_CHANGED,
        EVT_DELEGATE_RADIOBUTTON_CLICKED,

        EVT_WINDOW_SET_SIZE,
    };
}

#endif

